version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      time: "10:00"
      timezone: "America/Detroit"
    groups:
      "@remix-run":
        patterns:
          - "@remix-run/*"
      "@react-router":
        patterns:
          - "@react-router/*"
          - "react-router"
      "react":
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      "eslint":
        patterns:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "eslint"
          - "eslint-import-resolver-typescript"
          - "eslint-plugin-import"
          - "eslint-plugin-jsx-a11y"
          - "eslint-plugin-react"
          - "eslint-plugin-react-hooks"
